#!/bin/bash
rsync -a --delete ~/dev/suckless . 
rsync -a --delete ~/scripts . 

rm -rf suckless/st/.git
rm -rf suckless/dmenu/.git
rm -rf suckless/dwmstatus/.git
rm -rf suckless/dwm/.git

cp ~/.xinitrc .xinitrc 
cp ~/.bashrc .bashrc
